# Uncomment this line to define a global platform for your project
platform :ios, '15.0'

$FirebaseSDKVersion = '10.22.0'


# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

install! 'cocoapods', :deterministic_uuids => false


project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks! :linkage => :static

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
  pod 'Firebase/Crashlytics'

  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  strip_flag = lambda do |flags, flag|
    case flags
    when Array
      flags.reject { |value| value == flag }
    when String
      flags.split(' ').reject { |value| value == flag }.join(' ')
    else
      flags
    end
  end

  strip_flag_from_settings = lambda do |build_settings, flag|
    build_settings.each do |key, value|
      build_settings[key] = strip_flag.call(value, flag)
    end
  end

  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      config.build_settings['HEADER_SEARCH_PATHS'] = '$(inherited) "${PODS_ROOT}/Firebase/CoreOnly/Sources"'
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
      config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
      cxx_flags = config.build_settings['OTHER_CPLUSPLUSFLAGS']
      cxx_flags = cxx_flags.join(' ') if cxx_flags.is_a?(Array)
      cxx_flags = '$(inherited)' if cxx_flags.nil? || cxx_flags.empty?
      cxx_flags = cxx_flags.gsub(/-std=\S+/, '').strip
      cxx_flags = '$(inherited)' if cxx_flags.empty?
      config.build_settings['OTHER_CPLUSPLUSFLAGS'] = "#{cxx_flags} -fno-aligned-new"
      strip_flag_from_settings.call(config.build_settings, '-G')
      config.build_settings['OTHER_CFLAGS'] = strip_flag.call(config.build_settings['OTHER_CFLAGS'], '-G')
      config.build_settings['OTHER_CPLUSPLUSFLAGS'] = strip_flag.call(
        config.build_settings['OTHER_CPLUSPLUSFLAGS'],
        '-G'
      )
    end

    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
  end

  installer.aggregate_targets.each do |aggregate_target|
    aggregate_target.user_project.native_targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['CLANG_CXX_LANGUAGE_STANDARD'] = 'c++17'
        config.build_settings['CLANG_CXX_LIBRARY'] = 'libc++'
        cxx_flags = config.build_settings['OTHER_CPLUSPLUSFLAGS']
        cxx_flags = cxx_flags.join(' ') if cxx_flags.is_a?(Array)
        cxx_flags = '$(inherited)' if cxx_flags.nil? || cxx_flags.empty?
        cxx_flags = cxx_flags.gsub(/-std=\S+/, '').strip
        cxx_flags = '$(inherited)' if cxx_flags.empty?
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = "#{cxx_flags} -fno-aligned-new"
        strip_flag_from_settings.call(config.build_settings, '-G')
        config.build_settings['OTHER_CFLAGS'] = strip_flag.call(config.build_settings['OTHER_CFLAGS'], '-G')
        config.build_settings['OTHER_CPLUSPLUSFLAGS'] = strip_flag.call(
          config.build_settings['OTHER_CPLUSPLUSFLAGS'],
          '-G'
        )
      end
    end
  end
end
